### ISSUE TITLE
Wisper/Widespace

### ISSUE THREAD

**Issue by laurent-humbert** [wisper-rpc/wisper-js#3]
Hi there,

Using the latest version of the WSLibrary.framework in iOS, which we believe now uses Wisper, we noticed a bug. Intersticial ads sometimes only show for a split second then close, instead of waiting at least 5 seconds. We were able to reproduce the bug using Widespace's test environment and test intersticial. We've reported this bug to support@widespace.com but haven't received any reply.

I looked at JavaScript code for the ad, and sometimes it has autoCloseTime: "10" and sometimes autoCloseTime: "5".

As it seems to take about 5 seconds to actually show the ad, we think the timer should start *after* the ad had been displayed !

Any ideas on how to fix that?

**Comment by patriknyblad** [comment]
Hello Laurent,
I am no longer working for Widespace but stay connected to the Wisper Library since I like it very much. The proper support channel for the Widespace SDK is through support@widespace.com. 

I hope you get a response from them soon!
/Patrik
